### ISSUE TITLE
Convert BNToFloat to return string

### ISSUE THREAD

**Issue by AuroraLantean** [ggxchain/dex-ui#64]
Dangerous to convert BigNumbers to regular JS number!
Should convert BigNumbers to strings to display them, or keep them in BigNumbers to compare and calculate.

![Image](https://github.com/ggxchain/rfq-ui/assets/73493219/8ffa7041-fb0f-46f0-9959-694583a9c019)

**Comment by AuroraLantean** [comment]
Bug is fixed and pushed to https://github.com/ggxchain/rfq-ui/pull/65
But there is another bug: 
Dex page cannot make a new order. Error: Extrinsic dex.makeOrder expects 7 arguments, got 6. I think there is a bug in ggxnode because I am running the frontend code directly from the frontend main branch.

From Bohdan: Run a node (brooklyn) locally. Run a script from package.json which generates "interfaces" folder. Build again
From Artur: we had merged limit orders. That doesn't supported by frontend

**Comment by MaxVch** [comment]
I have chacked on source coed we are using 6 parameters.
I think task isn't valid
